apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygoat
  labels:
    app: pygoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygoat
  template:
    metadata:
      labels:
        app: pygoat
    spec:
      containers:
      - name: pygoat
        image: pygoat/pygoat
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pygoat
spec:
  type: LoadBalancer
  selector:
    app: pygoat
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 8000
      nodePort: 30003